Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "config-proxy.sh"
  config.vm.provision "shell", path: "install-package.sh"
  config.proxy.enabled = false

  config.vm.define "kubemaster" do |master|
    master.vm.box = "centos/7"
    master.vm.network "private_network", ip:"192.168.0.3", name: "VirtualBox Host-Only Ethernet Adapter #4", netmask:"255.255.255.224"
    master.vm.provider "virtualbox" do |v|
      v.cpus = 4
      v.memory = 4096
    end
    master.vm.disk :disk, size: "50GB", name: "kubemaster-gluster"
  end

  config.vm.define "kubeworker1" do |worker1|
    worker1.vm.box = "centos/7"
    worker1.vm.network "private_network", ip:"192.168.0.4", name: "VirtualBox Host-Only Ethernet Adapter #4", netmask:"255.255.255.224"
    worker1.vm.provider "virtualbox" do |d|
      d.cpus = 4
      d.memory = 4096
    end
    worker1.vm.disk :disk, size: "50GB", name: "kubeworker1-gluster"
  end

  config.vm.define "ansiblemaster" do |ansiblemaster|
    ansiblemaster.vm.box = "centos/7"
    ansiblemaster.vm.network "private_network", ip:"192.168.0.2", name: "VirtualBox Host-Only Ethernet Adapter #4", netmask:"255.255.255.224"
    ansiblemaster.vm.provider "virtualbox" do |d|
      d.cpus = 2
      d.memory = 2048
    end
    ansiblemaster.vm.disk :disk, size: "10GB", name: "ansible-gluster"
    ansiblemaster.vm.provision "shell", path: "install-python-and-git.sh"
    ansiblemaster.vm.provision "shell", path: "install-ansible.sh", privileged: false
  end
end